### ISSUE TITLE
Cannot save model structure as json file

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [cpuimage/SINet#1]
Hi, I think it's cool that you reproduced the SINet model for TensorFlow, but I got a problem with it.

According to Keras documentation (https://www.tensorflow.org/guide/keras/save_and_serialize), the model structure should be exportable with the `to_json()` method of the Keras model, but when I try it, I get the following error.
```
Traceback (most recent call last):
  File "model.py", line 431, in <module>
    main()
  File "model.py", line 426, in main
    json = model.to_json()
  File "D:\ProgramData\Anaconda3\envs\sinet-tf\lib\site-packages\tensorflow\python\keras\engine\training.py", line 2277, in to_json
    model_config = self._updated_config()
  File "D:\ProgramData\Anaconda3\envs\sinet-tf\lib\site-packages\tensorflow\python\keras\engine\training.py", line 2244, in _updated_config
    config = self.get_config()
  File "D:\ProgramData\Anaconda3\envs\sinet-tf\lib\site-packages\tensorflow\python\keras\engine\functional.py", line 650, in get_config
    return copy.deepcopy(get_network_config(self))
  File "D:\ProgramData\Anaconda3\envs\sinet-tf\lib\site-packages\tensorflow\python\keras\engine\functional.py", line 1349, in get_network_config
    layer_config = serialize_layer_fn(layer)
  File "D:\ProgramData\Anaconda3\envs\sinet-tf\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 250, in serialize_keras_object
    raise e
  File "D:\ProgramData\Anaconda3\envs\sinet-tf\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 245, in serialize_keras_object
    config = instance.get_config()
  File "D:\ProgramData\Anaconda3\envs\sinet-tf\lib\site-packages\tensorflow\python\keras\engine\training.py", line 2254, in get_config
    raise NotImplementedError
NotImplementedError
```
My guess is that there are some custom layers that cannot be serializable, but I can't be sure since I've seen no information about that on the web.
Do you have an idea of what might cause this?
Thank you

**Comment by cpuimage** [comment]
@RaphaelRoyerRivard check the latest commits, this issue has been resolved. 
If you need to save more configuration items,
you need to implement the "def get_config(self):" method for each function layer
